### ISSUE TITLE
can it support mobile phone?

### ISSUE THREAD

**Issue by cd0304** [garrickvan/ar-game-engine#1]
can it support mobile phone?

**Comment by garrickvan** [comment]
If base on my code, dev lang(vc++) and dev env(win7), The answer is no, the game engine is just a prototype from a book, you could pick your favorite mobile 3D game engine. the key is artoolkit (http://www.hitl.washington.edu/artoolkit/), you could try to rebuild artoolkit to run on mobile and build the api for your mobile phone 3D game engine, and then, you could build your mobile one ar game engine.
